const storageKey='daylight-planner-v1';
const initial={tasks:[{id:'1',text:'Sketch out the big idea',done:true},{id:'2',text:'Make time to learn',done:true},{id:'3',text:'Bring the first version to life',done:false}],focus:"Build something I'm proud of.",dark:false};
let state;try{state=JSON.parse(localStorage.getItem(storageKey))||structuredClone(initial);if(!Array.isArray(state.tasks))throw Error();}catch{state=structuredClone(initial)}
let filter='all',toastTimer;
const list=document.querySelector('#task-list'),focusInput=document.querySelector('#focus-input');
function notify(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{notify('Browser storage unavailable. Changes last for this visit.')}}
function render(){list.replaceChildren();const visible=state.tasks.filter(task=>filter==='all'||(filter==='done'?task.done:!task.done));visible.forEach(task=>{const row=document.createElement('div');row.className='task-row'+(task.done?' done':'');const check=document.createElement('button');check.className='task-check';check.textContent=task.done?'✓':'';check.setAttribute('aria-label',(task.done?'Mark incomplete: ':'Complete: ')+task.text);check.setAttribute('aria-pressed',String(task.done));check.onclick=()=>{task.done=!task.done;save();render()};const name=document.createElement('span');name.className='task-name';name.textContent=task.text;const remove=document.createElement('button');remove.className='delete-task';remove.textContent='×';remove.setAttribute('aria-label','Delete: '+task.text);remove.onclick=()=>{state.tasks=state.tasks.filter(item=>item.id!==task.id);save();render();notify('Task removed')};row.append(check,name,remove);list.append(row)});document.querySelector('#empty-state').hidden=visible.length>0;const done=state.tasks.filter(task=>task.done).length,total=state.tasks.length;document.querySelector('#progress-number').textContent=done+'/'+total;document.querySelector('#progress-fill').style.width=(total?done/total*100:0)+'%';document.querySelector('#progress-message').textContent=total&&done===total?'All done. Make room for a little rest.':done+' small '+(done===1?'win':'wins')+'. Keep going at your pace.';document.querySelector('#clear-done').disabled=done===0;document.body.classList.toggle('dark',state.dark);document.querySelector('.theme-button').setAttribute('aria-label',state.dark?'Switch to light theme':'Switch to dark theme')}
document.querySelector('#task-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#task-input'),text=input.value.trim();if(!text){input.value='';input.focus();return}state.tasks.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),text,done:false});input.value='';filter='all';updateFilters();save();render();input.focus();notify('A new step, ready when you are')});
function updateFilters(){document.querySelectorAll('[data-filter]').forEach(button=>{button.classList.toggle('active',button.dataset.filter===filter);button.setAttribute('aria-pressed',String(button.dataset.filter===filter))})}
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;updateFilters();render()});document.querySelector('#clear-done').onclick=()=>{state.tasks=state.tasks.filter(task=>!task.done);save();render();notify('Completed tasks cleared')};focusInput.value=state.focus;focusInput.addEventListener('input',()=>{state.focus=focusInput.value;save()});document.querySelector('.theme-button').onclick=()=>{state.dark=!state.dark;save();render()};render();
